#!/bin/csh -f

# Usage
#    run_testsuite <testsuite_name>
#
# Example:
#    run_testsuite tau2020_testsuite0130

if ("$1" == "") then
  echo Usage:  $0 testsuite_name
  exit
endif

# dataset name
set dataset = $1

# enable pi models?
set pimodels = ""
set pimodels = "--pimodels"

# File containing Liberty models in CCS form
set library = "../../ASAP7_PDKandLIB_v1p6/lib_release_191006/asap7_7p5t_library/rev25/LIB/CCS/asap7sc7p5t_INVBUF_RVT_TT_ccs_191031.postprocessed.lib"

###########################################
# This section run once for the contest
#
# All contestants will use the same $dataset.circuits.yaml file.
###########################################

# Generate random dataset 
# output will be $dataset.circuits.yaml and $dataset.spef
../build/gen_random_nets --liberty $library --dataset $dataset -n 10 $pimodels --waveform asu_exp

# Generate SPICE-based golden results for benchmarking
set spice_decks = "spice_decks.$dataset"
set spice_lib = "../../ASAP7_PDKandLIB_v1p6/lib_release_191006/asap7_7p5t_library/rev25/CDL/xAct3D_extracted/Extracted_netlists/asap7sc7p5t_INVBUF_RVT.sp.modified"
set spice_models = "../../ASAP7_PDKandLIB_v1p6/asap7PDK_r1p6/models/hspice/7nm_TT.pm.modified"

################################################################
# This section is run once for each contestant
################################################################

# Run contestant's simulation
#   input:  $dataset.circuits.yaml
#   output: $dataset.dc.circuits.yaml
../build/delay_calc_tool \
  --circuits $dataset.circuits.yaml \
  --liberty $library \
  --spef $dataset.spef \
  --dc_file $dataset.dc.circuits.yaml

# Merge spice results contestant's results into *.merged.circuits.yaml and analyze results
#  input:  $dataset.dc.circuits.yaml
#  input:  $spice_decks
#  output: $dataset.merged.circuits.yaml
../build/delay_calc_tool \
  --circuits $dataset.dc.circuits.yaml \
  --spice_dir $spice_decks \
  --simulator xyce \
  --merged_circuits $dataset.merged.circuits.yaml




