#!/bin/csh -f

# Usage
#    run_testsuite <testsuite_name>
#
# Example:
#    run_testsuite tau2020_testsuite0130

if ("$1" == "") then
  echo Usage:  $0 testsuite_name
  exit
endif

# dataset name
set dataset = $1

# File containing Liberty models in CCS form
set library = "../../ASAP7_PDKandLIB_v1p6/lib_release_191006/asap7_7p5t_library/rev25/LIB/CCS/asap7sc7p5t_INVBUF_RVT_TT_ccs_191031.postprocessed.lib"

# pointers to SPICE results
set spice_decks = "spice_decks.$dataset"
set spice_lib = "../../ASAP7_PDKandLIB_v1p6/lib_release_191006/asap7_7p5t_library/rev25/CDL/xAct3D_extracted/Extracted_netlists/asap7sc7p5t_INVBUF_RVT.sp.modified"

################################################################
# This section is run once for each contestant
################################################################

# Run contestant's simulation
#   input:  $dataset.circuits.yaml
#   output: $dataset.dc.circuits.yaml
../build/delay_calc_tool \
  --circuits $dataset.circuits.yaml \
  --liberty $library \
  --spef $dataset.spef \
  --dc_file $dataset.dc.circuits.yaml

# Merge spice results contestant's results into *.merged.circuits.yaml and analyze results
#  input:  $dataset.dc.circuits.yaml
#  input:  $spice_decks
#  output: $dataset.merged.circuits.yaml
../build/delay_calc_tool \
  --circuits $dataset.dc.circuits.yaml \
  --spice_dir $spice_decks \
  --simulator xyce \
  --merged_circuits $dataset.merged.circuits.yaml




