#!/bin/csh -f

# This script shows how to generate a random set of parasitics and
# then read it into the delay calculator

# dataset name
set dataset = tau2020v1

# enable pi models?
set pimodels = ""
set pimodels = "--pimodels"

# File containing Liberty models in CCS form
set library = "NangateOpenCellLibrary_typical_ccs.adjusted.lib"

# Generate random dataset
# output will be $dataset.circuits.yaml and $dataset.spef
../build/gen_random_nets --liberty $library --dataset $dataset -n 100 $pimodels

# Read results into delay calculation tool
set spice_decks = "spice_decks"
set spice_lib = "../../NangateOpenCellLibrary_PDKv1_3_v2010_12/Back_End/lpe_spice/NangateOpenCellLibrary_lpe.spi"
set spice_models = "../../OpenROAD-Utilities/TimerCalibration/Free45PDK/gpdk45nm.m"
rm -rf $spice_decks
mkdir $spice_decks
../build/delay_calc_tool \
  --circuits $dataset.circuits.yaml \
  --liberty $library \
  --spef $dataset.spef \
  --spice_lib $spice_lib \
  --spice_models $spice_models \
  --spice_dir $spice_decks




